# Generated by Django 3.2.20 on 2023-08-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_like_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='featured_description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
