# Generated by Django 3.2 on 2024-02-15 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_like_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_placeholder',
            new_name='image',
        ),
    ]
